In [ ]:
# https://www.kaggle.com/utsav15/100-numpy-exercises?fbclid=IwAR3mMw4NuAUeTE_pF7XZSrMIm_N-qjJt-xpudE0X1dqUU2bbpAdfW_rgLRI

In [2]:
#1 import the numpy package
import numpy as np 

In [3]:
#2 print the numpy version and the configuration
print(np.__version__)
np.show_config()

1.19.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [5]:
#3 create a null vector of size 5
Z = np.zeros(5)
print(Z)

[0. 0. 0. 0. 0.]


In [6]:
#4 find the memory size of any array
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize)) 

800 bytes


In [7]:
#5 get documentation of numpy add function from the command line 
%run 'python -c "import numpy; numpy.info(numpy.add)"'

Exception: File `"'python.py"` not found.

In [8]:
#6 create a null vector of size 5, fifth value which is 1 
Z = np.zeros(5)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1.]


In [10]:
#7 create a vector with values ranging from (a,b)
#syntax: Z = np.arange(a,b+1)

Z = np.arange(10,20)
print(Z)


[10 11 12 13 14 15 16 17 18 19]


In [11]:
##8 reverse a vector (first element becomes last)
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [12]:
#9 create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#10 find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4], dtype=int64),)


In [14]:
#11 create a 3x3 identity matrix 
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#12. Create a 3x3x3 array with random values
Z = np.random.random((3,3,3))
print(Z)

[[[0.01660362 0.09982667 0.81028455]
  [0.62250307 0.22323761 0.50282298]
  [0.38148519 0.71110309 0.73314474]]

 [[0.17298433 0.81265136 0.16378428]
  [0.06693796 0.93213852 0.86482032]
  [0.32157197 0.59051974 0.49452641]]

 [[0.23231238 0.44736875 0.97727724]
  [0.76333174 0.29995507 0.28434624]
  [0.86839538 0.84502739 0.77276189]]]


In [23]:
#13 Create a 10x10 array with random values and find the minimum and maximum values
Z = np.random.random((10,10))
print('min of Z = ', Z.min())
print('max of Z = ', Z.max())


min of Z =  0.010657722345816745
max of Z =  0.9944943414167248


In [24]:
#14 Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
print('mean of Z=', Z.mean())

mean of Z= 0.5271131265811905


In [25]:
# 15 Create a 2d array with 1 on the border and 0 inside
Z = np.ones((5,5))
Z[1:-1, 1:-1]=0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
#16 How to add a border (filled with 0's) around an existing array?
Z = np.ones((5,5))
Z = np.pad(Z, pad_width= 2, mode='constant', constant_values = 0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
# 17. What is the result of the following expression?
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan -np.nan)
print(np.nan in set([np.nan]))
print(0.3== 3*0.1)

nan
False
False
nan
True
False


In [39]:
#18 Create a 4x4 matrix with values 1,2,3,4 just below the diagonal
Z= np.diag(1+np.arange(4))
print(Z)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [40]:
#18' Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z= np.diag(1+np.arange(4), k =-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [43]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8), dtype = int)
Z[1::2, ::2] =2 # bắt đầu từ hàng 1, khoảng cách là 2 hàng. cột chẵn

Z[::2, 1::2] =1
print(Z)

[[0 1 0 1 0 1 0 1]
 [2 0 2 0 2 0 2 0]
 [0 1 0 1 0 1 0 1]
 [2 0 2 0 2 0 2 0]
 [0 1 0 1 0 1 0 1]
 [2 0 2 0 2 0 2 0]
 [0 1 0 1 0 1 0 1]
 [2 0 2 0 2 0 2 0]]


In [46]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100, (5,6,7)))


(2, 2, 2)


In [48]:
# 21. Create a checkerboard 8x8 matrix using the tile function
Z = np.tile(np.array([[1,2],[3,4]]), (4,4))
print(Z)

[[1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]
 [1 2 1 2 1 2 1 2]
 [3 4 3 4 3 4 3 4]]


In [50]:
#22 Normalize a 5x5 random matrix 
Z = np.random.random((5,5))
Z = (Z - np.mean(Z))/(np.std(Z))
print(Z)


[[-1.24054595 -0.55847442  0.98249843 -1.55090965  0.6729317 ]
 [ 1.34682163 -0.83781321  0.37892769  0.73338469 -0.35055691]
 [-1.76721512  1.43492942 -1.11631703 -0.12943807  1.08838777]
 [-0.96656716 -1.10656323  0.09159838  0.93504188 -0.38794893]
 [ 0.21902331  0.20340589  1.96776082 -0.80273944  0.76037753]]


In [51]:
#23 Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-51-4e19e84e10af>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [52]:
#24 Multiply a 5x3 matrix by a 3x2 matrix 
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [53]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [54]:
# 26. What is the output of the following script? 
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [55]:
# 27. Consider an integer vector Z, which of these expressions are legal?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

In [56]:
# 28. What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-56-1b6e6186873e>:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-56-1b6e6186873e>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [57]:
# 29. How to round away from zero a float array ?
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ -7.  -1.  -5.   9.   3.  -8.  -8.  -4.  -4. -10.]


In [58]:
# 30. How to find common values between two arrays?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


[2 3 6 7 8]


In [59]:
# 31. How to ignore all numpy warnings (not recommended)?
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-59-07541a83d5f7>, line 9)

In [60]:
# 32. Is the following expressions true? 
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-60-25ac1801789c>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [61]:
# 33. How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')


In [62]:
# 34. How to get all the dates corresponding to the month of July 2016?
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [63]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A) 

array([-1.5, -1.5, -1.5])

In [66]:
# 36. Extract the integer part of a random array using 5 different methods
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[5. 8. 4. 3. 0. 3. 8. 5. 2. 0.]
[5. 8. 4. 3. 0. 3. 8. 5. 2. 0.]
[5. 8. 4. 3. 0. 3. 8. 5. 2. 0.]
[5 8 4 3 0 3 8 5 2 0]
[5. 8. 4. 3. 0. 3. 8. 5. 2. 0.]


In [65]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 
Z = np.zeros((5,5)) 
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [64]:
# 38. Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype= float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [67]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
Z = np.linspace(0,1,11, endpoint = False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [68]:
#40 create a random vector of size 10 and sort it 
Z = np.random.random(10)
Z.sort()
print(Z)

[0.12765184 0.14261376 0.41143056 0.43651169 0.4481879  0.44821263
 0.50518824 0.61539341 0.86528057 0.89889545]


In [70]:
#41 How to sum a small array faster than np.sum?
Z = np.arange(10)
np.add.reduce(Z)

45

In [71]:
#42 Consider two random array A and B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


In [72]:
#43 make an array immutable (read-only)
Z =np.zeros(10)
Z.flags.writeable = False 
Z[0] = 1

ValueError: assignment destination is read-only

In [73]:
#44 Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
# (chuyển đổi từ tọa độ Cartesian sang tọa độ cực)
Z = np.random.random((10,2))
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.90584946 0.64508204 0.26627112 0.88307023 0.65586143 0.58518606
 0.96900591 0.29325973 0.60240309 0.34113259]
[1.28501029 0.85542159 0.72935478 0.21286989 1.31295557 1.28920113
 0.98810275 1.00802387 0.96708677 0.36965344]


In [77]:
#45 create random vector of size 5 and replace the maximum value by 0 
Z = np.random.random(5)
print(Z)
print(Z.max())
Z[Z.argmax()] = 0
print(Z)

[0.38973106 0.37033802 0.2790125  0.20368732 0.05305411]
0.38973106462845875
[0.         0.37033802 0.2790125  0.20368732 0.05305411]


In [78]:
#46 create a structured array with x and y coordinates covering the [0,1]x[0,1] area 
Z = np.zeros((5,5), [('x', float), ('y', float)])
Z['x'], Z['y'] =np.meshgrid(np.linspace(0,1, 5 ),
                            np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [83]:
#47. given two arrays, X and Y, construct the Cauchy matrix C (Cij  = 1/(xi-yj)) 
X = np.arange(8)
Y = X + 0.5
C = 1.0/ np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


In [80]:
#48 print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [92]:
#49. How to print all the values of an array ?
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [101]:
#50 how to find the closet value ( to given scalar) in a vector?
Z = np.arange(100)
v = np.random.uniform(0,100)
# print(Z)
# print(v)
# print(abs(Z-v))
index = (np.abs(Z-v)).argmin()
print(Z[index])

10
